crossing_planes_multiHead:
  policy: "MaskedMultiOutputPolicy"
  n_timesteps: !!float 1e7
  n_envs: 8                                      
  gamma: 0.99
  learning_rate: !!float 3e-4
  batch_size: 4096
  ent_coef: 0.02
  normalize: "dict(norm_obs=True, norm_reward=True)"
  normalize_advantage: true
  env_wrapper:
    - stable_baselines3.common.monitor.Monitor
  callback:
    - "custom_envs.info_logger_callback.LogAllInfoCallback"
  policy_kwargs: "dict(
                    net_arch=dict(pi=[], vf=[128, 128])
                  )"

