crossing_planes_multiHead:
  policy: "MaskedMultiOutputPolicy"
  n_timesteps: !!float 1e6
  n_envs: 6                                      
  gamma: 0.96
  learning_rate: lin_1e-4
  ent_coef: 0.001
  normalize: "dict(norm_obs=True, norm_reward=True)"
  normalize_advantage: true
  env_wrapper:
    - stable_baselines3.common.monitor.Monitor
  callback:
    - "custom_envs.info_logger_callback.LogAllInfoCallback"
  policy_kwargs: "dict(
                    net_arch=dict(pi=[128, 128], vf=[128, 128])
                  )"

LunarLander-v3:
  policy: "MaskedMultiOutputPolicy"
  n_timesteps: !!float 2e6
  n_envs: 16
  n_steps: 1024
  batch_size: 64
  gae_lambda: 0.98
  gamma: 0.999
  n_epochs: 4
  ent_coef: 0.01
  env_wrapper:
    - custom_envs.lunarlander_multioutput.LunarLanderMultiOutput