LunarLanderContinuous-v3:
  n_envs: 16
  n_timesteps: !!float 4e6
  policy: 'MaskedHybridPolicy'
  n_steps: 1024
  batch_size: 64
  gae_lambda: 0.98
  gamma: 0.999
  n_epochs: 4
  ent_coef: 0.01
  env_wrapper:
    - custom_envs.lunarlander_continuous_multioutput.LunarLanderContinuousMultiOutput
  policy_kwargs: "dict(
                  net_arch=dict(pi=[], vf=[64, 64])
                )"
